[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
gcd = "2.3"
rustc-hash = "1.1"
reqwest = { version = "0.11", features = ["blocking"] }
